// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEeAGosNuAdeCD-pnpNJvVkYGMza1YEJM',
    appId: '1:314200360531:web:6e6798e5fd0bf9efb728a6',
    messagingSenderId: '314200360531',
    projectId: 'manga-app-1d850',
    authDomain: 'manga-app-1d850.firebaseapp.com',
    storageBucket: 'manga-app-1d850.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9f_esggG-WN7kA37ryQs_rv9is8E1yXQ',
    appId: '1:314200360531:android:dd40956cddde8687b728a6',
    messagingSenderId: '314200360531',
    projectId: 'manga-app-1d850',
    storageBucket: 'manga-app-1d850.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDX-LoeJ70VnvFmt6iLXwZBz1saIcyFaE',
    appId: '1:314200360531:ios:9dfc666a32b2dbe8b728a6',
    messagingSenderId: '314200360531',
    projectId: 'manga-app-1d850',
    storageBucket: 'manga-app-1d850.appspot.com',
    iosBundleId: 'com.example.mangaAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDX-LoeJ70VnvFmt6iLXwZBz1saIcyFaE',
    appId: '1:314200360531:ios:9dfc666a32b2dbe8b728a6',
    messagingSenderId: '314200360531',
    projectId: 'manga-app-1d850',
    storageBucket: 'manga-app-1d850.appspot.com',
    iosBundleId: 'com.example.mangaAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEeAGosNuAdeCD-pnpNJvVkYGMza1YEJM',
    appId: '1:314200360531:web:1f16381608e93611b728a6',
    messagingSenderId: '314200360531',
    projectId: 'manga-app-1d850',
    authDomain: 'manga-app-1d850.firebaseapp.com',
    storageBucket: 'manga-app-1d850.appspot.com',
  );
}
